### ISSUE TITLE
linux deploy couldn't find these debs : 0

### ISSUE THREAD

**Issue by issamouu** [meefik/linuxdeploy#190] opened 2015-02-06 00:09 UTC
I have a galaxy tab 2 10.1 rooted 
Android 4.0.3
![screenshot_2015-02-06-00-07-35](https://cloud.githubusercontent.com/assets/4654885/6072028/66725040-ad94-11e4-9612-799a3d0f6c48.png)

**Comment by meefik** [comment] 2015-02-21 20:58
Fixed in verstion 1.5.0-132

**Closed by meefik** 2015-02-21 20:58 UTC

**Comment by dhblocker** [comment] 2015-05-22 16:05
Hello,

just stumbled upon the same Problem on Lenovo vibe z2 pro android 5.0.2 rooted. It happens on all Debian based distros and all of the versions.

Regardd

**Comment by meefik** [comment] 2015-05-22 19:06
Hmm, I'll check it out. It may be a problem with the file pkgdetails. Try to execute the following line and put here the results:

    /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails

**Comment by dhblocker** [comment] 2015-05-22 19:23
root@kingdom_row:/ # /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails
tmp-mksh: /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails: can't execute: Permission denied

**Comment by meefik** [comment] 2015-05-22 19:24
ls -l /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/

**Comment by dhblocker** [comment] 2015-05-22 19:40
k.linuxdeploy/linux/deploy/debootstrap/pkgdetails         <
/system/bin/sh: /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails: not found
127|u0_a129@kingdom_row:/ $ su
root@kingdom_row:/ # /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails
tmp-mksh: /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails: can't execute: Permission denied
root@kingdom_row:/ # ls -l /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/
-rw------- u0_a18   u0_a18        699 2015-05-22 18:24 devices.tgz
-rw------- u0_a18   u0_a18      36097 2015-05-22 18:24 functions
-rw------- u0_a18   u0_a18      68204 2015-05-22 18:24 pkgdetails
drwx------ u0_a18   u0_a18            2015-05-22 18:24 scripts
root@kingdom_row:/ #

**Comment by dhblocker** [comment] 2015-05-22 19:41
sorry it pasted much more than needed....

**Comment by meefik** [comment] 2015-05-22 20:04
After chmod 755 it works?

**Comment by dhblocker** [comment] 2015-05-22 21:07
thanks for the great support, I will be able to check that tomorrow, will let you know

**Comment by RSA99** [comment] 2015-05-22 22:13
I'm getting exactly the same problem on SM-N9005.
I chmod 755 pkgdetails 
but, linux deploy seems to overwrite the result and I am back to square 1

**Comment by dhblocker** [comment] 2015-05-23 21:13
chmod 755 /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails

is working for me. Thanks!

**Comment by levyguy88** [comment] 2015-05-28 20:53
I have this same problem I'm kinda new to linux and commands and stuff. If someone could please help me it would be greatly appreciated! Thanks!

**Comment by levyguy88** [comment] 2015-05-28 20:53
I have a rooted LG G3 just so you know...

**Comment by zefram12** [comment] 2015-06-14 06:40
Nexus 6 running stock lollipop 5.1.

I can confirm that changing the permission of the pkgdetails file is only temporary. I've tried chmod & es file explorer. It does look like linux deploy is changing the permission back when starting the download. Perhaps it's some form of security implemented in lollipop?

Cannot get past the "debs : 0" problem. Looks to be easier to prepare an image for chroot manually from a workstation.

**Comment by bamsbamx** [comment] 2015-06-15 22:40
This one worked also for me, do the following just before clicking INSTALL:
chmod 755 /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails

Worked with Android 5.1Lollipop with Nexus 7 (flo), getting Ubuntu Trusty from http://ftp.tu-chemnitz.de/pub/linux/ubuntu-ports/

**Comment by Levy8Me** [comment] 2015-06-15 22:52
I don't understand bamsbamx i typed that into the terminal and it didn't do anything it still doesn't work.

**Comment by Levy8Me** [comment] 2015-06-15 22:58
I have a LG G3 running Lollipop 5.0.1

**Comment by zefram12** [comment] 2015-06-16 05:48
At some point after clicking download the pkgdetails doesn't exist anymore. I think linux deploy removes the directory and recreates it with wrong permissions. 

Don't laugh, but I was finally able to get it working with a simple loop in sh:

a=0
while [ $a -lt 10 ]
do
  ls -l /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails
  chmod 755 /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails
  ls -l /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails
   sleep 1
done

**Comment by bamsbamx** [comment] 2015-06-16 08:50
@Levy8Me you must insert the following two commands (WITHOUT QUOTES)

-"su"
-"chmod 755 /data/data/ru.meefik.linuxdeploy/linux/deploy/debootstrap/pkgdetails"

Then go to Linux deploy and click the arrow down button in the action bar and finally install

**Comment by zefram12** [comment] 2015-06-16 08:57
@bamsbamx  That didn't work for me, because on my phone the permissions is reset after clicking install. Your advice can possibly work if one time it just right at some point AFTER clicking the install.

**Comment by Levy8Me** [comment] 2015-06-23 00:36
@zefram12 Thank you sooo much man you're the best!

**Comment by jeffhoyo** [comment] 2015-08-01 04:44
I have tried these commands on a kind of rooted Droid Turbo and they are not working. There is not a full working root method for the Droid TUrbo. We do have root but not full RW to system files, which seems like it is needed for Linux Deploy to install a Linux VM in Android OS.

**Comment by jeffhoyo** [comment] 2015-08-05 15:37
I did find out that if I kept a Teminal Open on my device and continued to enter the chmod command, it was able to "find these debs" haha. Just takes a little bit of timing. Thanks for the help.

**Comment by anyonehacks** [comment] 2015-08-15 18:31
I too have same problem on my rooted mi3 on parandroid ROM (5.1). When I enter chmod it doesn't do anything . I even changed the path to legacy instead of 0 . still same problem help me.plz
