### ISSUE TITLE
Arch Linux extra/ssh start failed

### ISSUE THREAD

**Issue by CainSakura** [meefik/linuxdeploy#1129] opened 2019-10-28 04:55 UTC
I'm using aarch64 architecture. Debug log output like this
```
[11:02:03] ## extra/ssh : do_start
[11:02:03] :: Starting extra/ssh ... ls: /data/local/mnt/etc/ssh/: No such file or directory
[11:02:03] -bash: ssh-keygen: command not found
[11:02:03] -bash: /usr/sbin/sshd: No such file or directory
[11:02:03] fail
```

**Comment by Danct12** [comment] 2019-10-31 00:48
Have you went to the three dots button and click "Install"?

**Comment by CainSakura** [comment] 2019-11-01 02:06
> Have you went to the three dots button and click "Install"?

Yes I clicked "Install", the other parts of system installed correctly, but extra/ssh does not work. I think there maybe something missing but I'm not sure. I tried "Configure" return the same result. Now I'm using Debian without this problem.

**Comment by Danct12** [comment] 2019-11-05 03:36
Can you try again with Linux Deploy 2.5.0? Seems like it fixed something on Arch Linux. (check changelog.md)

**Comment by CainSakura** [comment] 2019-11-06 08:35
I updated to 2.5.0, but this issue still exists. [Here's my log.](https://pastebin.com/5Utvkhr0)

```
[15:55:12] looking for conflicting packages...
[15:55:12] 
[15:55:12] Packages (23) bash-5.0.011-1  db-5.3.28-4  dnssec-anchors-20190629-1  e2fsprogs-1.45.4-1  filesystem-2019.10-1  gcc-libs-8.3.0-1  gdbm-1.18.1-2  glibc-2.29-1  iana-etc-20191031-1  keyutils-1.6.1-1  krb5-1.17-1  ldns-1.7.1-1  libedit-20191025_3.1-1  libldap-2.4.48-1  libsasl-2.1.27-1  libutil-linux-2.34-3  linux-api-headers-5.3.1-1  ncurses-6.1-6  openssl-1.1.1.d-1  perl-5.30.0-3.1  readline-8.0.001-1  tzdata-2019c-2  openssh-8.1p1-1
[15:55:12] 
[15:55:12] Total Download Size:    54.91 MiB
[15:55:12] Total Installed Size:  260.58 MiB
[15:55:12] :: Proceed with installation? [Y/n] + rm -f '/data/local/mnt/var/cache/pacman/pkg/*'
[15:55:12] + exit 0
[15:55:12] + return 0
[15:55:12] + do_configure
[15:55:12] + msg ':: Configuring extra/ssh ... '
[15:55:12] + echo ':: Configuring extra/ssh ... '
[15:55:12] :: Configuring extra/ssh ... 
[15:55:12] + local sshd_config
[15:55:12] + sshd_config=/data/local/mnt/etc/ssh/sshd_config
[15:55:12] + sed -i -E 's/#?PasswordAuthentication .*/PasswordAuthentication yes/g' /data/local/mnt/etc/ssh/sshd_config
[15:55:12] sed: /data/local/mnt/etc/ssh/sshd_config: No such file or directory
[15:55:12] + sed -i -E 's/#?PermitRootLogin .*/PermitRootLogin yes/g' /data/local/mnt/etc/ssh/sshd_config
[15:55:12] sed: /data/local/mnt/etc/ssh/sshd_config: No such file or directory
[15:55:12] + sed -i -E 's/#?AcceptEnv .*/AcceptEnv LANG/g' /data/local/mnt/etc/ssh/sshd_config
[15:55:12] sed: /data/local/mnt/etc/ssh/sshd_config: No such file or directory
[15:55:12] + return 0
```

I noticed that the script deleted all package when there's an installation confirm message, causes nothing installed in extra/ssh.

**Comment by Danct12** [comment] 2019-11-08 02:15
That's weird. I've never seen this before.

**Comment by Andersonfeng** [comment] 2019-11-12 10:39
Hi

My device is aarch64 and installed centos 7 aarch64

I was block by this problem few days ago

And I try a lot ways to fix this like reinstall the linux-deploy & busybox and change image, adb remount ...

Finally I work it out through change the source address to alibaba ...
`https://mirrors.aliyun.com/centos-altarch/`

**Comment by Danct12** [comment] 2019-11-13 01:38
That's for CentOS, doesn't work on Arch.
Also the problem you have is caused by bad mirrors, but here we don't get this problem.

**Comment by tommaso-perondi** [comment] 2019-11-15 06:39
Yeah, can confirm i nave this issue with arch, it just exit before actually installing openssh and so it can't find the configuration file nor start the service.

**Comment by HoshiYamazaki** [comment] 2019-11-21 17:00
Can confirm that, fresh Arch installation hangs on extra/ssh.

**Comment by tommaso-perondi** [comment] 2019-11-21 17:11
A simple fix (user side) is to mount the image, chroot into it and manually install openssh, this way you can click configure and let it do the thing. The only problem is that pacman will say that the file are already present on the file system, but if you pass ' --overwrite="*" ' it should not break the system and work anyway.

**Comment by meefik** [comment] 2019-11-21 19:12
I add this fix
https://github.com/meefik/linuxdeploy-cli/commit/f98d79df69b8ed84d166eeeeb719fa4f8775ac7f

**Comment by tommaso-perondi** [comment] 2019-11-21 19:30
> I added this fix
> [meefik/linuxdeploy-cli@f98d79d](https://github.com/meefik/linuxdeploy-cli/commit/f98d79df69b8ed84d166eeeeb719fa4f8775ac7f)

Wow thanks, first time i help someone on github!

**Comment by top1Ashier** [comment] 2019-11-30 03:49
I got the same problem ,but now i think i find a solution download the mirror manually.Then you can install arch by using rootfs.

**Comment by HoshiYamazaki** [comment] 2019-12-18 08:52
@meefik when you will release new version of Linux Deploy, because I think this issue is really important to fix?

**Comment by OverSurge** [comment] 2019-12-29 22:38
Hello, I have the same problem. It prevents me to use Arch with LinuxDeploy. I look forward to this being resolved :)

**Comment by OverSurge** [comment] 2019-12-31 11:24
Fixed with the latest release, thank you ^^

**Closed** 2019-12-31 11:37 UTC

**Comment by janostudio** [comment] 2020-02-10 13:36
> That's for CentOS, doesn't work on Arch.
> Also the problem you have is caused by bad mirrors, but here we don't get this problem.

When execute 'Insatlling extra/ssh...', the resoure can't be downloaded from the determing fatest mirrors in China.
