### ISSUE TITLE
Can you support fedora 23 and 24?

### ISSUE THREAD

**Issue by zjzdy** [meefik/linuxdeploy#524] opened 2016-06-12 15:51 UTC
Fedora 24 Beta is released,But linuxdeploy not support fedora 23.
And I try to change 22 to 23,But have some question.
Configuring the container: 
[23:44:28] dns ... done
[23:44:28] mtab ... done
[23:44:28] misc ... done
[23:44:28] groups ... done
[23:44:31] repository ... done
[23:44:31] Installing minimal environment: 
[23:44:31] Yum command has been deprecated, use dnf instead.
[23:44:31] See 'man dnf' and 'man yum2dnf' for more information.
[23:44:32] There was a problem importing one of the Python modules
[23:44:32] required to run yum. The error leading to this problem was:
[23:44:32] 
[23:44:32]    libnghttp2.so.14: cannot open shared object file: No such file or directory
[23:44:32] 
[23:44:32] Please install a package which provides this module, or
[23:44:32] verify that the module is installed correctly.
[23:44:32] 
[23:44:32] It's possible that the above module doesn't match the
[23:44:32] current version of Python, which is:
[23:44:32] 2.7.10 (default, Sep  8 2015, 17:36:20) 
[23:44:32] [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
[23:44:32] 
[23:44:32] If you cannot solve this problem yourself, please go to 
[23:44:32] the yum faq at:
[23:44:32]   http://yum.baseurl.org/wiki/Faq
[23:44:32]   
[23:44:32] <<< install

**Comment by zjzdy** [comment] 2016-06-14 11:21
add that pkg dnf dnf-conf dnf-yum dnf-langpacks dnf-langpacks-conf dnf-plugins-core hawkey python3 python3-six python3-dnf python3-dnf-langpacks python3-dnf-plugins-core python3-libs python3-hawkey python3-iniparse python3-libcomps python3-librepo python3-pygpgme libsolv rpm-python3 libcomps libnghttp2 librepo passwd can resolution question.

**Comment by zjzdy** [comment] 2016-06-15 10:35
But also have many question.vnc can't connection and ssh don't set password.

**Comment by kxra** [comment] 2016-08-28 21:44
duplicate of #399

**Comment by meefik** [comment] 2016-10-20 08:56
Added Fedora 24 in version 2.0

**Closed by meefik** 2016-10-20 08:56 UTC
