### ISSUE TITLE
error in vnc viewer

### ISSUE THREAD

**Issue by svralkar30** [meefik/linuxdeploy#739] opened 2017-02-27 07:18 UTC
The port on which computer is listening for connection could not be contacted

**Comment by svralkar30** [comment] 2017-02-28 06:19
Give me solution please

**Comment by CodeDem** [comment] 2017-03-03 16:28
Hey svralkar30 ,

Please be more descriptive with your error and if possible help with a screen shot attachment
also which port number you are using?

**Comment by joaopa00** [comment] 2017-03-11 02:02
That is a well known problem. This a duplicate of bug #694

There, you will find a workaround to fix the problem. Anyway, it would be nice that this bug is fixed in Linuxdeploy

**Comment by findmenowzero** [comment] 2017-05-24 07:16
This is not a bug
Check the settings aginst this 
https://github.com/meefik/linuxdeploy/wiki/Installing-Kali-Linux-Guide

**Closed** 2019-07-22 08:35 UTC
