### ISSUE TITLE
Only Black Screen when using Framebuffer for Display

### ISSUE THREAD

**Issue by expanses** [meefik/linuxdeploy#45] opened 2013-05-01 07:10 UTC
I'm having trouble getting the framebuffer option to work. My phone only displays a black screen and my tablet usually does the same (usually the menu bar at the bottom goes away and then comes back), although it occasionally displays the desktop and then freezes and turns black after switching apps. Where tablet's menu bar is (with back, home, etc buttons), the image is distorted. The back and home buttons can still be pressed through the screen (the framebuffer mode uses the whole screen and covers them). Both devices I used clean installs of Ubuntu quantal with armhf and installed xserver-xorg-input-mtrack. xinit xserver-xorg xserver-xorg-video-fbdev xserver-xorg-input-evdev are all installed. Frame Buffer settings are Display 2, Video device /dev/graphics/fb0, Input device /dev/input/event2. 

With debugging messages enabled in Linux Deploy, after <<< end: start, it displays some of the Xorg.2.log and after the "Initializing built-in extension..." messages, the last thing it says is "Loading extension GLX".

I tried Ubuntu precise, armhf  and Ubuntu quantal, armel on my tablet as well.

Also, it skips the Frame Buffer part (Frame Buffer... skip) if VNC is enabled, even if Frame Buffer is checked in the Properties menu.

Here's the /var/log/Xorg.2.log from each device:

LG Optiums G -- Black Screen

```
[  9058.271] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[  9058.272] X Protocol Version 11, Revision 0
[  9058.272] Build Operating System: Linux 3.2.0-1419-omap4 armv7l Ubuntu
[  9058.273] Current Operating System: Linux localhost 3.0.21 #1 SMP PREEMPT Fri Nov 23 15:20:24 KST 2012 armv7l
[  9058.273] Kernel command line: vmalloc=600M console=ttyHSL0,115200,n8 lpj=67677 user_debug=31 msm_rtb.filter=0x0 ehci-hcd.park=3 androidboot.hardware=geeb uart_console=disable lge.rev=rev_10 lcd_maker_id=primary is.hreset=off lge.reset=mode_reset gpt=enable logoentry=0x0+0+0 cable_type=12 androidboot.emmc=true androidboot.serialno=dc4ba159 lge.signed_image=true androidboot.baseband=mdm
[  9058.275] Build Date: 09 October 2012  04:08:45AM
[  9058.275] xorg-server 2:1.13.0-0ubuntu6 (For technical support please see http://www.ubuntu.com/support) 
[  9058.276] Current version of pixman: 0.26.0
[  9058.276]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[  9058.276] Markers: (--) probed, (**) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  9058.280] (==) Log file: "/var/log/Xorg.2.log", Time: Wed Apr 24 18:55:42 2013
[  9058.282] (==) Using config file: "/etc/X11/xorg.conf"
[  9058.283] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  9058.289] (==) ServerLayout "Layout0"
[  9058.289] (**) |-->Screen "Screen0" (0)
[  9058.289] (**) |   |-->Monitor "<default monitor>"
[  9058.293] (**) |   |-->Device "Card0"
[  9058.293] (==) No monitor specified for screen "Screen0".
    Using a default monitor configuration.
[  9058.294] (**) |-->Input Device "touchscreen"
[  9058.294] (==) Automatically adding devices
[  9058.294] (==) Automatically enabling devices
[  9058.294] (==) Automatically adding GPU devices
[  9058.298] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  9058.298]    Entry deleted from font path.
[  9058.298] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  9058.298]    Entry deleted from font path.
[  9058.298] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  9058.298]    Entry deleted from font path.
[  9058.298] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  9058.298]    Entry deleted from font path.
[  9058.299] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  9058.299]    Entry deleted from font path.
[  9058.299] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  9058.299]    Entry deleted from font path.
[  9058.300] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[  9058.301]    Entry deleted from font path.
[  9058.301] (==) FontPath set to:
    /usr/share/fonts/X11/misc,
    built-ins
[  9058.301] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  9058.301] (II) The server relies on udev to provide the list of input devices.
    If no devices become available, reconfigure udev or disable AutoAddDevices.
[  9058.301] (II) Loader magic: 0x40171e68
[  9058.301] (II) Module ABI versions:
[  9058.301]    X.Org ANSI C Emulation: 0.4
[  9058.301]    X.Org Video Driver: 13.0
[  9058.301]    X.Org XInput driver : 18.0
[  9058.301]    X.Org Server Extension : 7.0
[  9058.303] Initializing built-in extension Generic Event Extension
[  9058.303] Initializing built-in extension SHAPE
[  9058.303] Initializing built-in extension MIT-SHM
[  9058.304] Initializing built-in extension XInputExtension
[  9058.304] Initializing built-in extension XTEST
[  9058.305] Initializing built-in extension BIG-REQUESTS
[  9058.305] Initializing built-in extension SYNC
[  9058.306] Initializing built-in extension XKEYBOARD
[  9058.306] Initializing built-in extension XC-MISC
[  9058.306] Initializing built-in extension SECURITY
[  9058.307] Initializing built-in extension XINERAMA
[  9058.307] Initializing built-in extension XFIXES
[  9058.308] Initializing built-in extension RENDER
[  9058.308] Initializing built-in extension RANDR
[  9058.309] Initializing built-in extension COMPOSITE
[  9058.309] Initializing built-in extension DAMAGE
[  9058.309] Initializing built-in extension MIT-SCREEN-SAVER
[  9058.310] Initializing built-in extension DOUBLE-BUFFER
[  9058.310] Initializing built-in extension RECORD
[  9058.311] Initializing built-in extension DPMS
[  9058.311] Initializing built-in extension X-Resource
[  9058.311] Initializing built-in extension XVideo
[  9058.311] Initializing built-in extension XVideo-MotionCompensation
[  9058.311] Initializing built-in extension XFree86-VidModeExtension
[  9058.311] Initializing built-in extension XFree86-DGA
[  9058.311] Initializing built-in extension XFree86-DRI
[  9058.311] Initializing built-in extension DRI2
[  9058.311] (II) LoadModule: "glx"
[  9058.325] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  9058.335] (II) Module glx: vendor="X.Org Foundation"
[  9058.335]    compiled for 1.13.0, module version = 1.0.0
[  9058.335]    ABI class: X.Org Server Extension, version 7.0
[  9058.335] (==) AIGLX enabled
[  9058.336] Loading extension GLX
[  9058.336] (II) LoadModule: "fbdev"
[  9058.339] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[  9058.342] (II) Module fbdev: vendor="X.Org Foundation"
[  9058.342]    compiled for 1.12.99.902, module version = 0.4.3
[  9058.342]    Module class: X.Org Video Driver
[  9058.342]    ABI class: X.Org Video Driver, version 13.0
[  9058.342] (II) LoadModule: "evdev"
[  9058.344] (II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[  9058.349] (II) Module evdev: vendor="X.Org Foundation"
[  9058.349]    compiled for 1.13.0, module version = 2.7.3
[  9058.349]    Module class: X.Org XInput Driver
[  9058.349]    ABI class: X.Org XInput driver, version 18.0
[  9058.349] (II) FBDEV: driver for framebuffer: fbdev
[  9058.350] (--) using VT number 2
```

Samsung Galaxy Note 10.1 -- Black Screen or Desktop that Freezes

```
[  1734.958] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[  1734.959] X Protocol Version 11, Revision 0
[  1734.959] Build Operating System: Linux 3.2.0-1419-omap4 armv7l Ubuntu
[  1734.959] Current Operating System: Linux localhost 3.0.31-813049 #1 SMP PREEMPT Fri Feb 22 16:39:26 KST 2013 armv7l
[  1734.959] Kernel command line: console=ttySAC2,115200 loglevel=4 sec_debug.level=0 sec_watchdog.sec_pet=5 androidboot.debug_level=0x4f4c sec_log=0x200000@0x46000000 s3cfb.bootloaderfb=0x5ec00000 sysscope=0xee000000 lcdtype=1 consoleblank=0 lpcharge=0 lpj=3981312 vmalloc=144m oops=panic pmic_info=1 cordon=8fac4e68d0003644b0161a0b90bdbd2c androidboot.emmc_checksum=3 androidboot.bootloader=N8013UEUCMB3 androidboot.serialno=41063d0b2a86af27 snd_soc_core.pmdown_time=1000
[  1734.960] Build Date: 09 October 2012  04:08:45AM
[  1734.960] xorg-server 2:1.13.0-0ubuntu6 (For technical support please see http://www.ubuntu.com/support) 
[  1734.961] Current version of pixman: 0.26.0
[  1734.961]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[  1734.961] Markers: (--) probed, (**) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  1734.962] (==) Log file: "/var/log/Xorg.2.log", Time: Wed Apr 24 18:28:20 2013
[  1734.963] (==) Using config file: "/etc/X11/xorg.conf"
[  1734.964] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  1734.970] (==) ServerLayout "Layout0"
[  1734.970] (**) |-->Screen "Screen0" (0)
[  1734.970] (**) |   |-->Monitor "<default monitor>"
[  1734.972] (**) |   |-->Device "Card0"
[  1734.972] (==) No monitor specified for screen "Screen0".
    Using a default monitor configuration.
[  1734.972] (**) |-->Input Device "touchscreen"
[  1734.972] (==) Automatically adding devices
[  1734.972] (==) Automatically enabling devices
[  1734.972] (==) Automatically adding GPU devices
[  1734.974] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  1734.974]    Entry deleted from font path.
[  1734.974] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  1734.974]    Entry deleted from font path.
[  1734.974] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  1734.974]    Entry deleted from font path.
[  1734.974] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  1734.974]    Entry deleted from font path.
[  1734.974] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  1734.974]    Entry deleted from font path.
[  1734.974] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  1734.975]    Entry deleted from font path.
[  1734.975] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[  1734.975]    Entry deleted from font path.
[  1734.975] (==) FontPath set to:
    /usr/share/fonts/X11/misc,
    built-ins
[  1734.975] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  1734.975] (II) The server relies on udev to provide the list of input devices.
    If no devices become available, reconfigure udev or disable AutoAddDevices.
[  1734.975] (II) Loader magic: 0x40242e68
[  1734.975] (II) Module ABI versions:
[  1734.975]    X.Org ANSI C Emulation: 0.4
[  1734.975]    X.Org Video Driver: 13.0
[  1734.975]    X.Org XInput driver : 18.0
[  1734.975]    X.Org Server Extension : 7.0
[  1734.976] Initializing built-in extension Generic Event Extension
[  1734.976] Initializing built-in extension SHAPE
[  1734.976] Initializing built-in extension MIT-SHM
[  1734.977] Initializing built-in extension XInputExtension
[  1734.977] Initializing built-in extension XTEST
[  1734.977] Initializing built-in extension BIG-REQUESTS
[  1734.977] Initializing built-in extension SYNC
[  1734.977] Initializing built-in extension XKEYBOARD
[  1734.977] Initializing built-in extension XC-MISC
[  1734.977] Initializing built-in extension SECURITY
[  1734.977] Initializing built-in extension XINERAMA
[  1734.978] Initializing built-in extension XFIXES
[  1734.978] Initializing built-in extension RENDER
[  1734.978] Initializing built-in extension RANDR
[  1734.978] Initializing built-in extension COMPOSITE
[  1734.978] Initializing built-in extension DAMAGE
[  1734.978] Initializing built-in extension MIT-SCREEN-SAVER
[  1734.978] Initializing built-in extension DOUBLE-BUFFER
[  1734.979] Initializing built-in extension RECORD
[  1734.979] Initializing built-in extension DPMS
[  1734.979] Initializing built-in extension X-Resource
[  1734.979] Initializing built-in extension XVideo
[  1734.979] Initializing built-in extension XVideo-MotionCompensation
[  1734.979] Initializing built-in extension XFree86-VidModeExtension
[  1734.979] Initializing built-in extension XFree86-DGA
[  1734.979] Initializing built-in extension XFree86-DRI
[  1734.980] Initializing built-in extension DRI2
[  1734.980] (II) LoadModule: "glx"
[  1734.982] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  1734.994] (II) Module glx: vendor="X.Org Foundation"
[  1734.994]    compiled for 1.13.0, module version = 1.0.0
[  1734.994]    ABI class: X.Org Server Extension, version 7.0
[  1734.994] (==) AIGLX enabled
[  1734.994] Loading extension GLX
[  1734.994] (II) LoadModule: "fbdev"
[  1734.996] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[  1734.998] (II) Module fbdev: vendor="X.Org Foundation"
[  1734.998]    compiled for 1.12.99.902, module version = 0.4.3
[  1734.998]    Module class: X.Org Video Driver
[  1734.998]    ABI class: X.Org Video Driver, version 13.0
[  1734.999] (II) LoadModule: "evdev"
[  1734.999] (II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[  1735.006] (II) Module evdev: vendor="X.Org Foundation"
[  1735.007]    compiled for 1.13.0, module version = 2.7.3
[  1735.007]    Module class: X.Org XInput Driver
[  1735.007]    ABI class: X.Org XInput driver, version 18.0
[  1735.007] (II) FBDEV: driver for framebuffer: fbdev
[  1735.007] (--) using VT number 2

[  1735.009] (WW) Falling back to old probe method for fbdev
[  1735.009] (II) Loading sub module "fbdevhw"
[  1735.009] (II) LoadModule: "fbdevhw"
[  1735.010] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[  1735.011] (II) Module fbdevhw: vendor="X.Org Foundation"
[  1735.011]    compiled for 1.13.0, module version = 0.0.2
[  1735.011]    ABI class: X.Org Video Driver, version 13.0
[  1735.011] (II) FBDEV(0): using /dev/graphics/fb0
[  1735.011] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  1735.011] (**) FBDEV(0): Depth 24, (--) framebuffer bpp 32
[  1735.011] (==) FBDEV(0): RGB weight 888
[  1735.011] (==) FBDEV(0): Default visual is TrueColor
[  1735.011] (==) FBDEV(0): Using gamma correction (1.0, 1.0, 1.0)
[  1735.011] (II) FBDEV(0): hardware: s3cfb (video memory: 8000kB)
[  1735.011] (**) FBDEV(0): Option "fbdev" "/dev/graphics/fb0"
[  1735.011] (II) FBDEV(0): checking modes against framebuffer device...
[  1735.011] (II) FBDEV(0): checking modes against monitor...
[  1735.011] (--) FBDEV(0): Virtual size is 1280x800 (pitch 1280)
[  1735.011] (**) FBDEV(0):  Built-in mode "current": 66.7 MHz, 49.4 kHz, 60.0 Hz
[  1735.012] (II) FBDEV(0): Modeline "current"x0.0   66.67  1280 1298 1314 1350  800 804 807 823 -hsync -vsync -csync (49.4 kHz b)
[  1735.012] (==) FBDEV(0): DPI set to (96, 96)
[  1735.012] (II) Loading sub module "fb"
[  1735.012] (II) LoadModule: "fb"
[  1735.012] (II) Loading /usr/lib/xorg/modules/libfb.so
[  1735.017] (II) Module fb: vendor="X.Org Foundation"
[  1735.017]    compiled for 1.13.0, module version = 1.0.0
[  1735.018]    ABI class: X.Org ANSI C Emulation, version 0.4
[  1735.018] (**) FBDEV(0): using shadow framebuffer
[  1735.018] (II) Loading sub module "shadow"
[  1735.018] (II) LoadModule: "shadow"
[  1735.018] (II) Loading /usr/lib/xorg/modules/libshadow.so
[  1735.021] (II) Module shadow: vendor="X.Org Foundation"
[  1735.021]    compiled for 1.13.0, module version = 1.1.0
[  1735.021]    ABI class: X.Org ANSI C Emulation, version 0.4
[  1735.021] (==) Depth 24 pixmap format is 32 bpp
[  1735.274] (==) FBDEV(0): Backing store disabled
[  1735.279] (==) FBDEV(0): DPMS enabled
[  1735.280] (==) RandR enabled
[  1735.367] (II) AIGLX: Screen 0 is not DRI2 capable
[  1735.367] (II) AIGLX: Screen 0 is not DRI capable
[  1735.439] (II) AIGLX: Loaded and initialized swrast
[  1735.439] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[  1735.504] (II) XKB: reuse xkmfile /tmp/server-B20D7FC79C7F597315E3E501AEF10E0D866E8E92.xkm
[  1735.510] (II) Using input driver 'evdev' for 'touchscreen'
[  1735.510] (**) Option "CorePointer"
[  1735.510] (**) touchscreen: always reports core events
[  1735.510] (**) evdev: touchscreen: Device: "/dev/input/event2"
[  1735.511] (--) evdev: touchscreen: Vendor 0 Product 0
[  1735.511] (--) evdev: touchscreen: Found 20 mouse buttons
[  1735.511] (--) evdev: touchscreen: Found keys
[  1735.511] (II) evdev: touchscreen: Forcing relative x/y axes to exist.
[  1735.511] (II) evdev: touchscreen: Configuring as mouse
[  1735.511] (II) evdev: touchscreen: Configuring as keyboard
[  1735.511] (**) evdev: touchscreen: YAxisMapping: buttons 4 and 5
[  1735.511] (**) evdev: touchscreen: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[  1735.511] (II) XINPUT: Adding extended input device "touchscreen" (type: KEYBOARD, id 6)
[  1735.511] (**) Option "xkb_rules" "evdev"
[  1735.511] (**) Option "xkb_model" "evdev"
[  1735.511] (**) Option "xkb_layout" "us"
[  1735.522] (II) XKB: reuse xkmfile /tmp/server-D378AD8F86E560F712A83EE36E4E5E92C595B9BD.xkm
```

I love the app though.

Thanks!!

**Comment by mionec1** [comment] 2016-01-24 16:10
felonwan,My phone is XiaoMi
MI-ONE C1,I am using Debian wheezy now(LD 1.5.5).I have been tried to start Xorg by handle in Android terminal:
Xorg :0 -sharevts vt0
But,it was failed.Am I right? Can you tell me?
I am sorry for my bad English!

**Comment by felonwan** [comment] 2016-01-25 06:08
Sorry, I don't know either. But had you stopped the android GUI before trying to start Xorg? The argument '-sharevts' is interesting, I have never used it. I didn't use LD since that time.

**Comment by mionec1** [comment] 2016-01-25 12:57
felonwan,I have been stopped Android UI before start Xorg.
The argument“-sharevts"is hear from meeflk
Now,“/dev/tty0”is still missing.

**Comment by mionec1** [comment] 2016-01-27 00:48
meeflk,I want to start Xorg by handle,I use this command:
Xorg :0
Then,I see:
Fatal server error:
xf86OpenConsole: Cannot find a free VT: Inappropriate ioctl for device.
Then,I use the second command:
Xorg :0 vt1
Then,I see:
Fatal server error:
xf86OpenConsole: Cannot open virtual console 1 (No such file or directory)
What should I do?

**Comment by twaik** [comment] 2018-08-20 20:13
Please, try to reproduce the bug on the latest LD version.

**Comment by twaik** [comment] 2018-09-06 16:37
Looks like the bug was fixed in the latest version.

**Closed** 2018-09-06 18:59 UTC
